### ISSUE TITLE
The migration document needs some fixes

### ISSUE THREAD

**Issue by dcgavril** [JoanZapata/android-iconify#102]
Hi! First of all, I want to thank you for this great library!

I was upgrading from 1.x to 2.x and while looking on the documentation for the migration, I have seen that for the layout items, instead of writing "com.joanzapata.iconify.**widget**.IconButton" it is written "com.joanzapata.iconify.*views*.IconButton".

Thanks!

**Comment by Damore** [comment]
I had the same issue and I realized that views should be replaced by widget

**Comment by JoanZapata** [comment]
Oops, thank you for reporting it!
