### ISSUE TITLE
about storePassword ICONIFY_SAMPLE_KEYSTORE_PASSWORD!

### ISSUE THREAD

**Issue by killpigman** [JoanZapata/android-iconify#105]
Error:(28, 0) Could not find property 'ICONIFY_SAMPLE_KEYSTORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=/Users/wangyidong1/Downloads/android-iconify-master/android-iconify-sample/keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=/Users/wangyidong1/Downloads/android-iconify-master/android-iconify-sample/keystore}.

**Comment by JoanZapata** [comment]
I'll fix it, in the meanwhile you can do this to prevent this error:

```
echo "ICONIFY_SAMPLE_KEYSTORE_PASSWORD=" >> ~/.gradle/gradle.properties
```

**Comment by JoanZapata** [comment]
Fixed in the develop branch

**Comment by killpigman** [comment]
remove "signingConfigs" , app can runing successfully。
What exactly does it do?

**Comment by JoanZapata** [comment]
As its name implies, it's the keystore password for the sample app.
It's used when I build the release to publish on the Play Store.
My [fix](https://github.com/JoanZapata/android-iconify/commit/c5d923b19e7f7e16bce1049999f56d050bccdac8) makes it optional, though it's still required to build the release version of the sample app.
