### ISSUE TITLE
Crash application

### ISSUE THREAD

**Issue by albertodam** [JoanZapata/android-iconify#108]
When exit with back button and return my application crash. In the log show this message:
Caused by: java.lang.IllegalArgumentException: Can't add twice the same font "iconify/android-iconify-fontawesome.ttf".

**Comment by JoanZapata** [comment]
You can't call twice `Iconify.with(new FontAwesomeModule())`, that's because I want to you to set it up in your `Application` class, not in your `Activity`.

**Comment by albertodam** [comment]
Ops!! Thanks

**Comment by albertodam** [comment]
Leave issue for the other user.

**Comment by JoanZapata** [comment]
I'll add the info directly in the error message and close this issue after that.

**Comment by JoanZapata** [comment]
Done in develop.
