### ISSUE TITLE
Calling IconDrawable.draw(Canvas) results in missing fill color for icon

### ISSUE THREAD

**Issue by and3rson** [JoanZapata/android-iconify#111]
I was just trying to combine a map marker icon with FontAwesomeIcon/MaterialIcon.
The problem is that resulting image is not filled. For example:

```java
        IconDrawable iconDrawable = new IconDrawable(
                context, icon
        ).color(
                context.getResources().getColor(R.color.primary_color)
        ).sizePx(64);
        // Let's create an empty bitmap...
        Bitmap iconBitmap = Bitmap.createBitmap(64, 64, Bitmap.Config.ARGB_8888);
        // ...and a corresponding Canvas
        Canvas iconCanvas = new Canvas(iconBitmap);
        iconDrawable.draw(iconCanvas);
        // At this point, iconBitmap contains only borders of an icon.
        // I tried with different icons with same result.
```

Here's a screenshot demonstrating a problem:

![Screenshot demonstrating the problem](https://habrastorage.org/files/f5b/40e/305/f5b40e3058e9492cb764b46bd3713eaa.jpg)

At the same time, other drawables (PNG etc) are drawn just fine using the same method.

Any ideas?
Thanks!

**Comment by JoanZapata** [comment]
Sorry, fixed in develop, will be released before monday.
