### ISSUE TITLE
Spin not working on Chinese 10" tablet (Jellybean)

### ISSUE THREAD

**Issue by ch-muhammad-adil** [JoanZapata/android-iconify#112]
I have compiled these two modules,
    compile 'com.joanzapata.iconify:android-iconify-material:2.0.8'
    compile 'com.joanzapata.iconify:android-iconify-fontawesome:2.0.8'

then in Application initialized these modules 
Iconify.with(new FontAwesomeModule())
                .with(new MaterialModule());

tried this as it is 

< com.joanzapata.iconify.widget.IconTextView
    android:text="{fa-heart spin}"
    android:shadowColor="#22000000"
    android:shadowDx="3"
    android:shadowDy="3"
    android:shadowRadius="1"
    android:textSize="40sp"
    android:textColor="#FFF"/>

then there was only little rotation in the heart icon, no rotation animation worked. even i have tried refresh icon. 

Anything I am missing ?

**Comment by JoanZapata** [comment]
I can't reproduce it. Using the exact same code the heart is spinning.
Is there anything you do programmatically on this `IconTextView`?
What's your phone and android version?

**Comment by ch-muhammad-adil** [comment]
So far I was doing nothing on it programmatically, but I have even tried it after that..  I am using jellybean and a 10" china tablet.

**Comment by ch-muhammad-adil** [comment]
Is it working fine at your end ???

**Comment by JoanZapata** [comment]
Yes it is. Anything in the logcat?

**Comment by ch-muhammad-adil** [comment]
ummm Sorry I haven't observed that.. I will let you know by morning for sure.. :) its too late here. 
for now I am using simple textview and will Iconify it programmatically. 
Just want to make sure will this spin or animation work programmatically or not ??? with same syntax "{fa-heart spin}". if it does then its fine if not then any method or example ?

**Comment by JoanZapata** [comment]
If you use `Iconify.addIcons(textView)` it does work the same as an `IconTextView`.
But make sure you call it again if you ever change the text of the `TextView`.

**Comment by ch-muhammad-adil** [comment]
textView.setText("{fa-heart spin}");
Iconify.addIcons(textView);

right ??

**Comment by JoanZapata** [comment]
Yes. Which is equivalent to this, by the way:
```java
textView.setText(Iconify.compute(this, "{fa-heart spin}", textView));
```

**Comment by ch-muhammad-adil** [comment]
it is a device issue. I have tested it at another device running on KITKAT works fine.

**Comment by ch-muhammad-adil** [comment]
one thing more any syntax for {iconname spin mycolor}?

**Comment by ch-muhammad-adil** [comment]
let me try on that device again if I can provide you log-cat.

**Comment by JoanZapata** [comment]
> one thing more any syntax for {iconname spin mycolor}?

Yes, please checkout the README file.

> it is a device issue. I have tested it at another device running on KITKAT works fine.

Thanks for your time. I'll try this on an emulator to see what's wrong with pre-4.4 devices.

**Comment by ch-muhammad-adil** [comment]
08-27 01:44:31.654  18273-18273/com.custom.views D/libEGL﹕ >>> 0 0 android
08-27 01:44:31.654  18273-18273/com.custom.views D/libEGL﹕ >>> 0 1 mali
08-27 01:44:31.657  18273-18273/com.custom.views D/libEGL﹕ loaded /system/lib/egl/libEGL_mali.so
08-27 01:44:31.659  18273-18273/com.custom.views D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_mali.so
08-27 01:44:31.662  18273-18273/com.custom.views D/libEGL﹕ loaded /system/lib/egl/libGLESv2_mali.so
08-27 01:44:31.666  18273-18273/com.custom.views E/linker﹕ load_library(linker.cpp:759): library "libmaliinstr.so" not found
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ appName=com.custom.views, acAppName=com.android.cts.openglperf
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ 0
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ appName=com.custom.views, acAppName=com.android.browser
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ 0

**Comment by ch-muhammad-adil** [comment]
between these line i think this is the main issue... 


08-27 01:44:31.666  18273-18273/com.custom.views E/linker﹕ load_library(linker.cpp:759): library "libmaliinstr.so" not found
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ appName=com.custom.views, acAppName=com.android.cts.openglperf
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ 0
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ appName=com.custom.views, acAppName=com.android.browser
08-27 01:44:31.669  18273-18273/com.custom.views E/﹕ 0

**Comment by ch-muhammad-adil** [comment]
Thank you soo much dear.. I really appreciate your help and concern.  :+1:  :+1: :100:

**Comment by luaz** [comment]
I didn't work on Samung Galaxy S3 running Android 4.3

  IconTextView iconTextView = (IconTextView) view.findViewById(R.id.iconTextView);
  iconTextView.setText("{fa-cog spin}");
