### ISSUE TITLE
Support Material design commmunity icons

### ISSUE THREAD

**Issue by keunes** [JoanZapata/android-iconify#113]
The [Material design icons project](https://materialdesignicons.com) ('the community edition') offers many additional valuable icons compared to the official Google material icons. Would it be an idea to complement/replace the Google set with the community set?

**Comment by JoanZapata** [comment]
Thanks, I didn't know about this one, I'll add it as a new module under the name `android-iconify-material-community`. If think the other one should still be an option.

**Comment by keunes** [comment]
That's great! And I think you're right in terms of keeping Google's official set as an option.

**Comment by JoanZapata** [comment]
Added in 2.0.9 released just now.
