### ISSUE TITLE
Any way to Iconify EditText/AutoCompleteTextView hints?

### ISSUE THREAD

**Issue by squeeish** [JoanZapata/android-iconify#122]
Has anyone found a way to do that?

**Comment by JoanZapata** [comment]
What is your need exactly? Allow the user to type anything and when he types `{fa-something}` the icon appear instead? I don't think that would be a good user experience.

**Comment by squeeish** [comment]
Nope, what I meant was to have something like:

    <AutoCompleteTextView
                android:id="@+id/actvSearch"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/hint_search_with_icon"
                />

Where `<string name="hint_search_with_icon">{fa-search} Search</string>`

I could do a drawableLeft and all that, but I was just wondering if this was possible :)

**Comment by JoanZapata** [comment]
Oh I see, you meant for the hint. It's definitely possible, I think all you have to do is to subclass `AutoCompleteTextView` and override `setHint(CharSequence)` like [this](https://github.com/JoanZapata/android-iconify/blob/master/android-iconify/src/main/java/com/joanzapata/iconify/widget/IconTextView.java#L32-L35).

Also, you might want to consider this lib: https://github.com/DayS/EnhancedEditText/

**Comment by JoanZapata** [comment]
@squeeish Does that answer you question?

**Comment by squeeish** [comment]
@JoanZapata my apologies, been busy these few days. I'll try it out now and update! :)

**Comment by JoanZapata** [comment]
No worry, I was just checking :)

**Comment by JoanZapata** [comment]
Closed due to inactivity.
