### ISSUE TITLE
i18n support problem

### ISSUE THREAD

**Issue by guobosheng** [JoanZapata/android-iconify#123]
Can I do something like this?

	<IconTextView
	    android:id="@+id/search"
	    android:layout_width="wrap_content"
	    android:layout_height="wrap_content"
	    android:text="@string/search_with_icon" />

Where `<string name="search_with_icon">{fa-search} Search</string>`
and  `<string name="search_with_icon">{fa-search} 搜索</string>`

**Comment by JoanZapata** [comment]
Yes. Since you opened an issue I guess you already tried and it didn't work. Have you properly registered the `FontAwesomeModule` in your `Application` ? (see readme)

**Comment by guobosheng** [comment]
Yes, I have registered the `FontAwesomeModule` in my `Application` , and it didn't work.

	Iconify.with(new FontAwesomeModule());

**Comment by guobosheng** [comment]
My apologies, now it works very well. Strange, what did I miss?

**Comment by JoanZapata** [comment]
You tell me:
- The iconify font awesome dependency declared in `build.gradle`
- The `FontAwesomeModule` registered in your `Application` (and `Application` properly declared in `AndroidManifest.xml`)
- The code you gave before for the `IconTextView` in your xml layout.

I'm closing for now, please reopen with details if you have this problem again.
