### ISSUE TITLE
fontawesome:2.1.0: Icon is still not vertically centered (like #115)

### ISSUE THREAD

**Issue by Tumanin** [JoanZapata/android-iconify#125]
here is the code:
```xml
 <com.joanzapata.iconify.widget.IconButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_alignParentRight="true"
        android:layout_marginTop="15dp"
        android:layout_marginBottom="15dp"
        android:paddingLeft="5dp"
        android:paddingRight="5dp"
        android:background="@drawable/button_actionbar"
        android:text="SIGN OUT {fa-sign-out}"
        android:singleLine="true"
        android:textColor="#ffffffff"
        android:textSize="12sp"/>
```
![screenshot_2015-09-22-21-12-42](https://cloud.githubusercontent.com/assets/8768467/10029024/14c165a2-6170-11e5-9d54-49dfbf09bf6d.jpeg)

**Comment by JoanZapata** [comment]
Rha... In fact, it would properly be well aligned with lowercase icons, but uppercase makes it look bad. I guess I'll have to add some control over the vertical alignment of icons.

**Comment by JoanZapata** [comment]
Starting from version 2.1.1 (release soon), `{fa-sign-out baseline}` will align the icon with the baseline of the text.

![14c165a2-6170-11e5-9d54-49dfbf09bf6d](https://cloud.githubusercontent.com/assets/675408/11304575/f690cb4c-8fa8-11e5-9286-8a47dd48ed8c.jpg)
