### ISSUE TITLE
Too many semicolons in documentation code sample and missing module

### ISSUE THREAD

**Issue by MarcinOrlowski** [JoanZapata/android-iconify#131]
In docs, you write:

    public class MyApplication extends Application {
		 @Override
		 public void onCreate() {
			  super.onCreate();
			  Iconify
					.with(new FontAwesomeModule())
					.with(new EntypoModule())
					.with(new TypiconsModule());
					.with(new MaterialModule());
					.with(new MeteoconsModule());
					.with(new WeathericonsModule());
					.with(new SimpleLineIconsModule());
					.with(new IoniconsModule());
		 }
    }

while is incorrect due to too much semi colons. It also lacks reference to `MaterialCommunityModule`. Correct version should look like this:

    public class MyApplication extends Application {
        @Override
        public void onCreate() {
            super.onCreate();
            Iconify
                .with(new FontAwesomeModule())
                .with(new EntypoModule())
                .with(new TypiconsModule())
                .with(new MaterialModule())
                .with(new MaterialCommunityModule())                 
                .with(new MeteoconsModule())
                .with(new WeathericonsModule())
                .with(new SimpleLineIconsModule())
                .with(new IoniconsModule());
        }
    }

**Comment by JoanZapata** [comment]
Fixed by #140 (thanks @msneujink)
