### ISSUE TITLE
NPE when calling getTypeFace

### ISSUE THREAD

**Issue by Orbyt** [JoanZapata/android-iconify#135]
Im simply trying to use this to create drawables to set as tab icons. I have `Iconify.with()` in my application class, and am using this for setting the icons:

```java
tabLayout.getTabAt(0).setIcon(new IconDrawable(this, FontAwesomeIcons.fa_share));
```

Getting this npe:

>Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Typeface com.joanzapata.iconify.internal.IconFontDescriptorWrapper.getTypeface(android.content.Context)' on a null object reference
            at com.joanzapata.iconify.IconDrawable.init(IconDrawable.java:63)
            at com.joanzapata.iconify.IconDrawable.<init>(IconDrawable.java:56)

Any ideas on what might be causing this?

**Comment by Svantulden** [comment]
Try using `Iconify.with(new FontAwesomeModule());`. I had this error too when I tried to use an `IonIcons` icon. I forgot to call `Iconify.with(new IoniconsModule());` also.

**Comment by JoanZapata** [comment]
Thanks @Svantulden. I added an explicit error message in case the module was not loaded.
