### ISSUE TITLE
[Question] Setting Toolbar menu item via XML

### ISSUE THREAD

**Issue by Plastix** [JoanZapata/android-iconify#136]
The readme has the following code:
```java
// Set an icon in the ActionBar
menu.findItem(R.id.share).setIcon(
   new IconDrawable(this, FontAwesomeIcons.fa_share)
   .colorRes(R.color.ab_icon)
   .actionBarSize());
```
Is there a way to do this with XML using the support library toolbar?

**Comment by JoanZapata** [comment]
I don't think so, you could probably put an IconTextView in the `Toolbar` directly in your layout file, but you'd loose some of the advantages of using a Toolbar. For example, the Toolbar wouldn't be able to adjust to smaller screen sizes by putting extra items in an overflow menu.

**Comment by Plastix** [comment]
Thanks for the explanation!
