### ISSUE TITLE
No icon appears for font-awsome; Lack of documentation for Material?

### ISSUE THREAD

**Issue by d3ancole1995** [JoanZapata/android-iconify#139]
So maybe I have understood your README file incorrectly.

When I run the app with a simple fontawsome icon added (exact as in the readme). The actual text shows up rather than the icon. What else do I need to do? I added the compile line to my app.gradle & initiated it with: Iconify.with(new FontAwesomeModule())

So what am I missing to get this working?

Also how do I use the material icons? I can't find you describing their usage anywhere

Many thanks

**Comment by Plastix** [comment]
I can't get the Material Design Icons to work. Testing on Android 6.0.

**Comment by JoanZapata** [comment]
The README as been updated for Material Design Icons.

@d3ancole1995: Where did you use `Iconify.with(new FontAwesomeModule())`. If in the `Application.onCreate()`, have you declared your Application in your `AndroidManifest.xml`?

**Comment by JoanZapata** [comment]
Closed due to inactivity, the original documentation issue has been fixed.
