### ISSUE TITLE
IconDrawable with multiple icons

### ISSUE THREAD

**Issue by muhammad-naderi** [JoanZapata/android-iconify#153]
Hi, 

in the `IconTextView` by simply concating the keys for the icons, one can creates a new icon contains two icons or more in a row, 

it would be nice if it was possible to be done for the `IconDrawable` as well, (to use as icon for menu items)

I was thinking, a new overload would be a good start: `public IconDrawable(Context context, List<Icon> icon)`

**Comment by JoanZapata** [comment]
Hi,

Thanks for the proposition, unfortunately I must keep a clear vision for this project and I don't see it as a common usecase. You can still create your own `Drawable` that draws itself by composing `IconDrawable`s to achieve this result.
