### ISSUE TITLE
Outlined icons on HiRes / API 23

### ISSUE THREAD

**Issue by appmagnetics** [JoanZapata/android-iconify#156]
We are using com.joanzapata.iconify:android-iconify-fontawesome:2.1.0 and experience weird visual effect which happens currently only using SDK 23 and high res screens: the icons which look "outlined" are from fontawesome, others are pure images. 

![screenshot_2016-02-07-15-51-00_720](https://cloud.githubusercontent.com/assets/7034162/12973403/6fa7c230-d0ac-11e5-81ea-1822ebb056a9.png)

**Comment by Tumanin** [comment]
solved, the problem was because we used the old code. We imported the new library (2.1.0), but had the old one in the folders and used it. Now it looks right.

**Comment by JoanZapata** [comment]
Good. :)
