### ISSUE TITLE
IconButton width is not correctly set with wrap_content

### ISSUE THREAD

**Issue by yigitserin** [JoanZapata/android-iconify#157]
Hi there,

I am using IconButton but I have a problem. When I set width to wrap_content, the width is bigger than it should be. Is there a way to correctly implement wrap_content?

Thanks!

**Comment by JoanZapata** [comment]
I'm not sure I understood correctly, can I see some code and screenshot please?

**Comment by yigitserin** [comment]
Hi there,

So when I wrap_content an ImageButton, it looks like 1. But I want it to be like 2. Is there any work around to do this?

[Here is Image](http://i.imgur.com/Upl7Gbn.png)

**Comment by JoanZapata** [comment]
I'll try to reproduce and fix it, but don't expect it to arrive very soon.

In the meantime, as a workaround, can you try using a standard `TextView` in your layout (with the same text as you have now) and programmatically do `Iconify.addIcons()` on this it?
