### ISSUE TITLE
Question: Advantages over png

### ISSUE THREAD

**Issue by ashwanikumar04** [JoanZapata/android-iconify#158]
Hello:
This is just for my information. What are the advantages using font icons over png icons?

**Comment by JoanZapata** [comment]
**Pros:**
- Smaller APK
- Smaller memory footprint
- No need to provide mdpi, xhdpi, etc... versions of each icons
- Quick color / size customization, without regenerating each icon
- Can be easily integrated into texts (a little bit of boilerplate is needed for PNGs, using spans)

**Cons:**
- You can't have two colors (like red and green) on the same icon. This is usually OK for icons, but it's a limitation to be aware of.

**Comment by ashwanikumar04** [comment]
Thanks :)
