### ISSUE TITLE
How to just use custom ttf file

### ISSUE THREAD

**Issue by ashwanikumar04** [JoanZapata/android-iconify#159]
Hi,
Iconify supports extensibility as mentioned in the Readme. However, I am not sure which gradle dependency to use in case I **just want to** extend iconify to use my custom ttf.

**Comment by JoanZapata** [comment]
```
compile 'com.joanzapata.iconify:android-iconify:2.2.1'
```

I just added it to the documentation.

**Comment by ashwanikumar04** [comment]
Thanks :)
