### ISSUE TITLE
Android Studio 0.8.6 dont render preview

### ISSUE THREAD

**Issue by gmarques33** [JoanZapata/android-iconify#52]
I dont know why, but android Studio dont render the preview when I`m using IconTextView.

**Comment by JoanZapata** [comment]
Putting `IconTextView` in `android.widget` was a hack, but as it seems to cause problems on some versions of the preview it will be moved on 2.0.0 to the Iconify package.

**Comment by JoanZapata** [comment]
Fixed by v2.
