### ISSUE TITLE
Cut word Kitkat

### ISSUE THREAD

**Issue by qcfer35** [JoanZapata/android-iconify#53]
Cut out some words when I use IconTextView,  if I use TextView works perfectly

![screenshot_2014-09-15-13-47-08](https://cloud.githubusercontent.com/assets/5713697/4276915/90c7c060-3d09-11e4-842b-0611446ce44d.png)

![screenshot_2014-09-15-13-49-06](https://cloud.githubusercontent.com/assets/5713697/4276914/90c5c6d4-3d09-11e4-9547-6d787ec58dba.png)

XML
<code>
&lt;LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginEnd="5dp"
    android:layout_marginRight="5dp"
    android:orientation="horizontal"
    android:padding="10sp" &gt;
&lt;android.widget.IconTextView
        android:id="@+id/iconTextView1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" /&gt;
&lt;/LinearLayout&gt;
</code>

tested on Android 4.4.4 Moto G

**Comment by JoanZapata** [comment]
Fixed by v2.
