### ISSUE TITLE
Use icons in EditText as drawables

### ISSUE THREAD

**Issue by danieljonker** [JoanZapata/android-iconify#54]
This is somewhat of a question/feature request as I'm not sure if this is already possible. But what I would like to achieve in the first instance would be to have something like:

<EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawableLeft="{icon}"
            />

Where the drawableLeft could be taken from font awesome, alternatively a programmatic way would suffice. I tried using: 
loginId.setCompoundDrawablesWithIntrinsicBounds(new IconDrawable(getActivity(), Iconify.IconValue.fa_adjust),0,0,0);

but it expects a drawable resource id.

Cheers

**Comment by 7wonders** [comment]
This works programmatically already:

```
mEmailView = (EditText) mLoginFormView.findViewById(R.id.email);
Drawable icon = new IconDrawable(getActivity(), Iconify.IconValue.fa_envelope).colorRes(R.color.holo_gray_light).actionBarSize();
mEmailView.setCompoundDrawables(icon, null, null, null);
mEmailView.setCompoundDrawablePadding(5);
```

**Comment by JoanZapata** [comment]
(and it won't work directly in xml because drawableLeft is expecting a drawable resource)
