### ISSUE TITLE
Compilation issue on second execution

### ISSUE THREAD

**Issue by OleksandrKucherenko** [JoanZapata/android-iconify#55]
I all the time got error "Multiple dex files define Landroid/widget/IconButton"

when i rebuild the project - everything works, but when i try to run second time, it fails.

I use gradle dependency:

```compile 'com.joanzapata.android:android-iconify:1.0.6'```

Any idea what can make this problem?

**Comment by JoanZapata** [comment]
@OleksandrKucherenko Did you get the bug back after upgrading?

**Comment by JoanZapata** [comment]
Closing for now, please reopen if the issue can be reproduced with latest build tools.
