### ISSUE TITLE
italic and bold text in textview

### ISSUE THREAD

**Issue by danieljonker** [JoanZapata/android-iconify#57]
Is the IconTextView able to handle italic and bold styles?

**Comment by ViliusKraujutis** [comment]
Looks like such code makes icons crappy:

    iconTextView.setTypeface(null, item.isImportant() ? Typeface.BOLD : Typeface.NORMAL);

**Comment by JoanZapata** [comment]
Version 2.0.0 should fix the problem. Available by the end of the week.

**Comment by ViliusKraujutis** [comment]
:+1: nice! Thank you.

**Comment by JoanZapata** [comment]
Fixed in develop, will be included in version `2.0.3`
