### ISSUE TITLE
FontAwesome animation such as fa-spin

### ISSUE THREAD

**Issue by fadils** [JoanZapata/android-iconify#62]
Is it in the roadmap?

Would be nice if we can add it just like fonts in the text attribute.

i.e. `android:text={fa-spin fa-spinner};`

**Comment by JoanZapata** [comment]
After a few tests myself, it **is** possible with spans, but it needs one more thing: have access to the TextView. I'll investigate to make sure it can't cause a leak and add it to the next version if it's ready at this time.

Syntax would be `{fa-something spin}`.

**Comment by JoanZapata** [comment]
Available in 2.0.7, released just now.
