### ISSUE TITLE
How to control the padding of the icons generated?

### ISSUE THREAD

**Issue by somghosh** [JoanZapata/android-iconify#67]
I am using the library as in the following code, and want to control the spacing between icons in actionbar. Is there a way? Thanks

    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        Log.d("LIFECYCLE", "OnCreateOptionsMenu() in MainActivity_");
        getMenuInflater().inflate(R.menu.menu_main_actionbar, menu);

        // Set an icon in the ActionBar
        menu.findItem(R.id.action_notification).setIcon(
                new IconDrawable(this, Iconify.IconValue.fa_bell)
                        .colorRes(R.color.white)
                        .actionBarSize());

        menu.findItem(R.id.action_tracking_setup).setIcon(
                new IconDrawable(this, Iconify.IconValue.fa_link)
                        .colorRes(R.color.white)
                        .actionBarSize());

        // set up the notification icon without badge if unreadNotifCount =0, else set the badge
        

        if(displayedUnreadNotifCount>0){
            ActionItemBadge.update(
                    this,
                    menu.findItem(R.id.action_notification),
                    new IconDrawable(this, Iconify.IconValue.fa_bell).colorRes(R.color.white).actionBarSize(),
                    ActionItemBadge.BadgeStyle.YELLOW,
                    displayedUnreadNotifCount);
            //unreadNotifCount);
        }
        else{
/*            menu.findItem(R.id.action_notification).setIcon(
                    new IconDrawable(this, Iconify.IconValue.fa_bell)
                            .colorRes(R.color.white)
                            .actionBarSize());*/
            ActionItemBadge.update(
                    this,
                    menu.findItem(R.id.action_notification),
                    new IconDrawable(this, Iconify.IconValue.fa_bell).colorRes(R.color.white).actionBarSize(),
                    ActionItemBadge.BadgeStyle.YELLOW,
                    -1);
        }
        return true;
    }

![2015-01-09](https://cloud.githubusercontent.com/assets/5731118/5719854/3e162410-9b14-11e4-910d-1b0d43dcbac7.png)

**Comment by mikepenz** [comment]
@somghosh the spacing between the icons is android default. As far as i know it's not possible to change this within a style. (not sure, perhaps you google for it or search @stackoverflow)

a different approach to get this is to create a custom view within the actionbar. you can find infos about this on the web, probably you can also get an idea how to do it by reading the sourcecode of https://github.com/mikepenz/Android-ActionItemBadge

cheers
