### ISSUE TITLE
Use with appCompat 21 Toolbar

### ISSUE THREAD

**Issue by Corey76** [JoanZapata/android-iconify#68]
How would we use this with the Toolbar icon in AppCompat v21?

This code errors:

mToolbar.setLogo(new IconDrawable(this, Iconify.IconValue.fa_share).colorRes(R.color.default_dark));

with:

java.lang.NoClassDefFoundError: com.joanzapata.android.iconify.IconDrawable

**Comment by mikepenz** [comment]
@Corey76 is it working anywhere else in your application? 
NoClassDefFoundError seems that the library isn't included. 
Do you use Android Studio with gradle?

**Comment by Corey76** [comment]
It wasn't working anywhere, and I was using Android Studio with gradle but then added the .jar file to the libs folder and it works now. I though gradled would get the library or something (obviously a noob in this) but all is working now :)

**Comment by mikepenz** [comment]
@Corey76 yeah but gradle should resolve it automatically (as soon as you add the compile dependency to your build.gradle) 

Please take a look at the sample how to use gradle (or how to add the dependency)

**Comment by Corey76** [comment]
I have:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.joanzapata.android:android-iconify:1.0.8'
}

but it was when I added the jar file it started working, maybe Im missing something?

**Comment by mikepenz** [comment]
@Corey76 normally this should be enough. do you use any other gradle dependencies?
Perhaps try it again, and resync the gradle file with the gradle button in the menu bar. should work. (it is easier if you can handle your libs with the gradle dependency)

**Comment by flaxie** [comment]
@mikepenz Hi. I have the same problem when i'm building the release package. When running from android studio it works but when i use "gradle clean assemble" the generated apk I get "java.lang.NoClassDefFoundError: com.joanzapata.android.iconify.IconDrawable"

**Comment by mikepenz** [comment]
@flaxie strange. i use Android Studio and gradle via the terminal and never had issues. this is no issue of this lib. 

do you use other gradle dependencies?

**Comment by flaxie** [comment]
@mikepenz I found the problem, it is proguard. Can you provide us with what exeptions to proguard that is needed?

**Comment by mikepenz** [comment]
@flaxie if it's proguard it should help to add following:

-keep class com.joanzapata.** { *; }

**Comment by JoanZapata** [comment]
Thanks @mikepenz, I just added it to the README.
