### ISSUE TITLE
Material Design Icons [ enhancement]

### ISSUE THREAD

**Issue by LOG-TAG** [JoanZapata/android-iconify#70]
I'm looking for material Design icons for this android-cionify with this icons https://github.com/google/material-design-icons

**Comment by mikepenz** [comment]
The android-iconify project is just about the FontAwesome icon-set.

There are other projects for the material-design-icons, like this one:
https://github.com/mikepenz/Android-Iconics

There's also a fork from the android-iconify library somewhere, which
includes the material-design-icons but i have no link.
