### ISSUE TITLE
Text font size shrinks when adding icon to TextView

### ISSUE THREAD

**Issue by Corey76** [JoanZapata/android-iconify#71]
I have 2 identical TextViews with 12dp for textSize and when I add an icon 
to the text "{fa-tag} sometag", the text shrinks by about 2dp, is this normal? 

I wouldn't expect the text size of the Text to change but it is, what can I do to maintain the textSize?

**Comment by JoanZapata** [comment]
Version 2.0.0 will fix the issue, available by the end of the week.

**Comment by JoanZapata** [comment]
Fixed by v2.
