### ISSUE TITLE
Combine two glyphs

### ISSUE THREAD

**Issue by emce** [JoanZapata/android-iconify#73]
It would be fine if there would be ability to combine two glyphs, for example: fa_user + fa_plus as add user (second as superscript or something). Maybe some spannable, I'm doing some research, if I come up with something, I'll get back...

**Comment by mikepenz** [comment]
@emce great. if you this is required a easy solution would be using a relativelayout and within this layout you can overlap two imageviews

**Comment by emce** [comment]
But creating view over views is not good pattern.

**Comment by mikepenz** [comment]
@emce yeah i know. for the best implementation we would require a custom draw method within the drawable which would handle multiple icons.

**Comment by mikepenz** [comment]
@emce or you create a LayerList http://stackoverflow.com/a/2740198/325479
