### ISSUE TITLE
Error Didn't find class “android.view.IconTextView”

### ISSUE THREAD

**Issue by slmyldz** [JoanZapata/android-iconify#76]
I asked stackoverflow that problem. There http://stackoverflow.com/questions/29247434/iconfy-library-didnt-find-class-android-view-icontextview

I added proguard rules.

**Comment by slmyldz** [comment]
I done it. I replace in xml layout "IconTextView" to "android.widget.IconTextView" . It's works successfully

**Comment by mikepenz** [comment]
@slmyldz great that you found the answer ;)
