### ISSUE TITLE
Android 5.0 textSize issue

### ISSUE THREAD

**Issue by squeeish** [JoanZapata/android-iconify#79]
I believe this issue is similar to #71 and #53 

Text in buttons, IconTextView and normal Textviews have the following effect.
(Exact same code on different devices)

Lollipop:
![Lollipop](http://i.imgur.com/Vmw8btW.png)

Below Lollipop:
![Below Lollipop](http://i.imgur.com/3CUsOmw.png)

**Comment by bakua** [comment]
Same issue here

**Comment by rajeshwaranP** [comment]
same issue here, have u got any solution

**Comment by JoanZapata** [comment]
I haven't tried to reproduce this error yet. Have you tried using `android:textAllCaps="false"` on it to see if this is somehow forced by lollipop ?
I can't think of any workaround for this at the moment sorry.

**Comment by JMu2014** [comment]
<code>android:textAllCaps="false"</code> solves the all caps problem, but not the misalignment issue.
That can be solved by <code>android:elegantTextHeight="true"</code>.
Using those 2, everything looks the same on Lollipop and below.

**Comment by squeeish** [comment]
`android:elegantTextHeight="true"` works, thanks.

**Comment by JoanZapata** [comment]
Will be fixed on 2.0.0, available by the end of the week.

**Comment by squeeish** [comment]
Awesome!

**Comment by JoanZapata** [comment]
Fixed by v2.
