### ISSUE TITLE
Bounds changed before draw cause rendering issue

### ISSUE THREAD

**Issue by wizwally** [JoanZapata/android-iconify#80]
Using the IconDrawable in a LayerDrawable could cause an issue in icon rendering. 
I experienced that bounds has been changed before the draw method is called causing an override of the size set earlier; maybe is better to set text height from the size specified or if equals to -1 to the current bounds height. 

I suggest this draw method that sizes correctly the icon if bounds has been changed and center the icon.
Maybe it would be useful to set a vertical/horizantal offset/padding of the icon.

```java
@Override
public void draw(Canvas canvas) {
    paint.setTextSize((this.size == -1) ? getBounds().height() : this.size);
    Rect textBounds = new Rect();
    String textValue = valueOf(icon.character);
    paint.getTextBounds(textValue, 0, 1, textBounds);
    float xOrigin = getBounds().left + (getBounds().width() / 2f);
    float yOrigin = getBounds().top + (getBounds().height() / 2f) + (textBounds.height() / 2f);
    canvas.drawText(textValue, xOrigin , yOrigin, paint);
 }
```

**Comment by JoanZapata** [comment]
Sorry for the delay, do you have an example code to show what the problem is using LayerDrawable, so that I can test your code in the right conditions?

**Comment by JoanZapata** [comment]
Closed due to inactivity. Feel free to reopen and provide additional info.
