### ISSUE TITLE
size-difference between letters and digits, gravity

### ISSUE THREAD

**Issue by AlexArmbruster** [JoanZapata/android-iconify#81]
Hello!
The image shows a IconTextView at the top and below a TextView. the copyright is an image just to try your library. The "my name," seems to be smaller than the "2015", and it looks being top-aligned. I tried with gravity="bottom", which makes no difference.
do you have an idea?
thanks,
Alex
![image](https://cloud.githubusercontent.com/assets/9800531/8066285/187e9d80-0ee7-11e5-8801-b806cbabf2c6.png)

**Comment by JoanZapata** [comment]
Are you on Lollipop? If so, can you try [this](https://github.com/JoanZapata/android-iconify/issues/79#issuecomment-104239201) and see if it works.

**Comment by JoanZapata** [comment]
Fixed by v2.
