### ISSUE TITLE
Icon button xml 

### ISSUE THREAD

**Issue by mgohin** [JoanZapata/android-iconify#83]
Hi,

when using xml widget like this

    <IconButton
                android:id="@+id/start_app"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:text="Launch app {fa-angle-right}" />

I got a square replacing icon because `IconButton.setText` is called twice (first time it finds `{fa-angle-right}` but not the second time).

Here is my conf if needed

    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "fr.arcacomputing.wincor.client"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

**Comment by JoanZapata** [comment]
Are you setting the typeface on it, or are you using something that might set the typeface of the IconButton?

**Comment by mgohin** [comment]
Hmmm yes I'm because I use set a custom Typefont in `onCreate` for all views, damned I'm stupid.
I'll skip set setTypeFace if it's an `IconButton`

Thanks
