### ISSUE TITLE
IconDrawable shows X in lollipop and blank in android 4... (within the actionbar)

### ISSUE THREAD

**Issue by rothschild86** [JoanZapata/android-iconify#88]
Any thoughts what might cause this? I know ttf is loaded because I'm not getting any exceptions... Thank you :)

**Comment by JoanZapata** [comment]
Can you provide a screenshot of the problem please? Are you sure you're not setting the typeface programmatically or in another way, through a library for example?

**Comment by rothschild86** [comment]
![2015-06-30_130020](https://cloud.githubusercontent.com/assets/4555882/8436668/0425657a-1f28-11e5-9184-fa141e2dfa93.png)

that's supposed to be fa-filter there...

code used:

```java
	public static void addMenuItem(Context context, Menu menu, int order, int textRes, int showAs, IconValue iconCode){
		
		MenuItem item = menu.add(0, textRes, order, textRes);
		
		item.setIcon(new IconDrawable(context, iconCode).actionBarSize());
		
		MenuItemCompat.setShowAsAction(item, showAs);	
	}
```

**Comment by rothschild86** [comment]
not using any typefaces anywhere else

**Comment by JoanZapata** [comment]
Fixed by v2.

**Comment by rothschild86** [comment]
cool
