### ISSUE TITLE
IconToggleButton is not callable in layout.xml.

### ISSUE THREAD

**Issue by rohnstock** [JoanZapata/android-iconify#89]
There is a IconToggleButton class, but it is not possible to call the class in the layout.xml.

**Comment by JoanZapata** [comment]
Try using `<android.widget.IconToggleButton ...>`.

**Comment by gte619n** [comment]
I cannot get this to work in the preview at all. It always says "The following classes could not be found: android.widget.IconTextView" when using the full path. If I switch to the simple name, it does not render the preview at all, nor does it report a failure.

I'm on build tools 22.0.1 and 1.0.9 of the lib. Compile SDK version is API 22.

Maybe an incompatibility there?

**Comment by JoanZapata** [comment]
Fixed by v2.
