### ISSUE TITLE
Problem when using words with "~" for example "Padrão" (Portuguese word)

### ISSUE THREAD

**Issue by Damore** [JoanZapata/android-iconify#92]
Hello,

I'm using the iconify and one of my buttons is like the  below:

![botao_iconify](https://cloud.githubusercontent.com/assets/4624254/8830939/6fa5c98a-3075-11e5-8707-2a496b137dd4.png)

However, the character " ã " is misaligned, probably because it is a portuguese word.

Any ideas?

**Comment by JoanZapata** [comment]
The whole string actually use the fontawesome typeface, so I don't think there's a workaround, you'd have to use 2 `TextView` side by side, the left one being an `IconTextView`.

**Comment by Damore** [comment]
I can't image how to do what you are suggesting to do... Can you show me an example?

**Comment by JoanZapata** [comment]
Sorry I didn't notice it was a button, which makes it harder.
I think the best way to go is to do it programmatically like :  
```
yourButton.setCompoundDrawablesWithIntrinsicBounds(
     new IconDrawable(context, IconValue.fa_save), 
     null, null, null)
```

(Don't forget to set the icon size and color on `IconDrawable` using setters.)

**Comment by JoanZapata** [comment]
@Damore I'm currently working on a V2 which would fix this problem. Hopefully it should be available by the end of the week. In the meanwhile you can still use the compoundDrawable as suggested.

**Comment by Damore** [comment]
Thank you very much!

**Comment by JoanZapata** [comment]
Fixed by v2.
